project:
  type: website

website:
  title: "Oziblue"
  navbar:
    left:
#      - href: festival.qmd
#        text: Home
      - href: rencontre.qmd
        text: Rencontre de dessin
      - about.qmd
#      - href: dessin_naturaliste.qmd
#        text: Dessin naturaliste      

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    toc-title: Contenu
    toc-location: left

editor: visual

extra_css:
  - stylesheets/extra.css

