project:
  type: website

website:
  title: "Oziblue"
  navbar:
    left:
#      - href: festival.qmd
#        text: Home
      - href: festival.qmd
        text: Festival
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    toc-title: Contenu
    toc-location: left

editor: visual

extra_css:
  - stylesheets/extra.css

