---
title: "Festival du dessin en plein air"
---

<!-- ## Festival du dessin en plein air -->

Avez-vous envie de vous déconnecter de l'agitation de la vie quotidienne et de vous reconnecter à la nature? Avez-vous envie de renforcer et stimuler votre créativité ?

REJOIGNEZ-NOUS le **30 avril 2026 à Savigny (CH-1073)**, pour un après-midi dédié à l'observation et à la contemplation de la nature par le dessin et l'activité créative. Nous proposons une rencontre de dessin en plein air, ouverte à toutes et à tous: débutant(e)s ou expert(e)s en dessin ou en peinture, enfants et adultes ! 

Vous pensez ne pas savoir dessiner ? Cela n'a pas d'importance ! L'objectif du festival n'est pas de réaliser une oeuvre d'art, mais de profiter de l'instant présent, d'observer et de contempler la nature par le dessin, et de se concentrer sur le processus plutôt que sur le résultat.

Une courte introduction de 15 minutes sur le sujet (technique et but) du dessin en plein air sera donnée à 14 heures, en début de festival (retrouvez l'introduction ici).

_Nous nous réjouisson de vous voir nombreux!_

<!-- > *No one will protect what they don't care about; and no one will care about what they have never experienced.* - Sir David Attenborough -->

> *Personne ne protégera ce qui ne l'intéresse pas; et personne ne s'intéressera à ce qu'il ne connaît pas.* - Sir David Attenborough

> *Voir le monde de ses yeux est mille fois mieux que n’importe quel rêve.* – Ray Bradbury


<!-- Inclure videos et photos -->

## Horaire et lieu

Le dimanche **30 avril 2026** de 14 heures à 17 heures.

Lien vers le lieu google maps et adresse (mis à jour le 23 avril 2026)

::: {.callout-important}
## Attention ! 

En cas de très mauvais temps, le lieu sera adapté ou la date reportée. 

Confirmation du lieu le 23 avril 2026
:::

## Matériel à emporter

_Très fortement recommendé :_
* Une gourde d'eau et un snack.  
* Protection solaire (chapeau et crème solaire). 
* Vêtements et chaussures adaptés à la [météo du jour](https://www.meteosuisse.admin.ch/previsions-locales/savigny/1073.html#forecast-tab=detail-view) et à la campagne.  
* Une chaise ou un tabouret de camping, pliable et/ou facile à transporter.

_Optionnel : _  
* Du matérial de dessin: un simple carnet à feuilles blanches ou des feuilles d'imprimantes et un crayon peuvent suffire.
* Un sous-main.  

Pour les personnes qui ne disposent pas de matériel de dessin, le matériel suivant sera mis à disposition gratuitement pour tout un chacun:  
* Feuilles de papier blanc.  
* Sous-main.   
* Crayons gris, gommes.  
* Crayons de couleur.  
* Aquarelles de plusieurs couleurs et [pinceaux à réservoir d'eau](https://www.carandache.com/ch/fr/pinceaux-estompes/pinceau-a-reservoir-d-eau-pointe-large-p-10404.htm).    
* [Stylos fins noirs](https://www.sakuraofamerica.com/product/pigma-micron/).  
* Stylos à encre aquarellable (["brush pens"](https://www.tomboweurope.com/en/products/product/ABT-N15)).  

Les personnes qui souhaitent partager leur matériel avec d'autres sont évidemment encouragées à le faire et nous les en remercions vivement!

## Contact et inscription

Pas besoin de forcément vous inscrire, vous pouvez simplement venir à l'heure qui vous convient le jour du festival, et rester autant de temps que vous le désirez. Nous serons présents pour vous guider et partager un moment artistique en plein air. 

Si vous n'avez pas de matériel de dessin, merci de nous écrire un petit message au 076, pour nous permettre de planifier au mieux les besoins en matériel pour tout le monde.

Pour être informé(e) des dernières mises à jour, rejoignez le groupe WhatsApp ici.

Le festival est gratuit ! Vous pourrez toutefois le soutenir en achetant l'une des cartes de voeux proposées lors de l'événement.

## Charte

* Je respecte la nature et le lieu : pas besoin d'arracher les plantes à outrance pour les dessiner. Je ramasse mes déchets. 
* Je ne me moque pas et je ne critique pas négativement les dessins des autres. Nous nous encouragons mutuellement.    
* Je ne m'auto-critique pas et j'ai un regard bienveillant sur mes propores créations.   
* Les enfants de tous âges sont les bienvenus, mais sous la responsabilité de leur(s) parent(s) ou d'une personne responsable. Les enfants peuvent aussi venir seuls mais ils doivent savoir s'autogérer; le festival ne fait pas office de service de garde.   
* J'emporte mes dessins avec moi lorsque je pars, mais je rends le matériel qui m'a été prêté. 

<!-- ## Exemples de dessins et peintures réalisés en plein air -->

<!-- ## Votre opinion sur le festival -->

<!-- lien vers le questionnaire à remplir après le festival -->

## Liens utiles

* 


